### ISSUE TITLE
overall-status links are broken

### ISSUE THREAD

**Issue by juhp** [dherrerace/willit-result#1]
Nice project - thank you for this

I noticed a small thing, that the overall-status links on the repo pages are broken.

ie they point to https://dherrerace.github.io/willit-result/status-overall.html
which is a 404.

**Comment by dherrerace** [comment]
Thanks for the report ^^
To fix this issue I reorganized things a little: now the generated files will get stored in the /willit folder, and https://dherrerace.github.io/willit-result/ will redirect you to https://dherrerace.github.io/willit-result/willit/status-overall.html
